### ISSUE TITLE
Add admin page 

### ISSUE THREAD

**Issue by ajaleelp** [ajaleelp/STH_15#1]
To approve pending registrations, also modify present user info (esp. reallocate team)

**Comment by rahulravindran2709** [comment]
Started work on this.Need help on the following use case
- Add a field called approvalStatus to user model.This can have values 'Pending' or 'Approved'
- If user registers for the event,create the user with pending status
- When admin logs in ,retrieve list of all users along with status
- If status is pending ,I will show a approve button
- Once admin clicks on the approve button,status gets changed to approved
- If user was approved earlier,he would still be shown along with a team list drop down and an update team button in order for the admin to change the team
- The update button calls the earlier updateUser service and changes the team details.
- We need to make sure the team chat channel the user is attached to is updated as well and he is no longer shown any previous or future messages from old team
  Will be giving the list of model/service changes needed below

**Comment by rahulravindran2709** [comment]
- Add a new updateUser service which will receive the json with updated fields and the username and update the details in db.This service can be used in 2 ways
  *Pass username and status as approved
  *Pass username and updated team name
- Add a getUsers service which will retrieve the total list of users hacing following details
  - User name
  - Team name
  - Approval status
- Add a getAllTeams service which will retrieve the total list of teams currently participating 
  I will make these urls and sample jsons in the xls

**Comment by rahulravindran2709** [comment]
Mobile view 

![image](https://cloud.githubusercontent.com/assets/7100759/5592062/b18974a2-91d6-11e4-9a0e-f63fdd6dbad6.png)

Desktop view
![image](https://cloud.githubusercontent.com/assets/7100759/5592064/d9b8ef84-91d6-11e4-89a7-36b9f2a72f6f.png)

Once the approve is clicked each individual notification changes to this

Mobile view
![image](https://cloud.githubusercontent.com/assets/7100759/5592069/2cbd28a8-91d7-11e4-94cb-c1f2b14cdad5.png)

![image](https://cloud.githubusercontent.com/assets/7100759/5592070/33b8fa2e-91d7-11e4-91a9-13362dce1d5e.png)

Desktop view
![image](https://cloud.githubusercontent.com/assets/7100759/5592067/08590284-91d7-11e4-82ff-7632f1377a84.png)
